### ISSUE TITLE
How to remove selected ids after process

### ISSUE THREAD

**Issue by ghost** [Pretius/pretius-smart-checkbox-column#2]
Thank you for this greate plugin.

I just want to ask a question: how do i remove the selected ids from APEX-ITEM, like your example Apex Mailbox.
1- In the received email report (Apex Mailbox), I select for example 3 rows, APEX-ITEM shows id of 3 rows - e.g: 28:268:20
2- Then I delete 3 selected rows.
3- I noticed the report is refreshed (not sure how specifically)
4- Then, if I select other rows, APEX-ITEM does not show 28:268:20 anymore.

In my application, at step 4, APEX-ITEM still re-recognizes 28:268:20 even though 3 rows have been deleted and are no longer in the report.

**Comment by akierzkowski** [comment]
Pretius Smart Checkbox Column plugin is always initiated on a DOM element with a static id being a combination of yourReportStaticId_columnStaticId_pscc. In the example from application demo it’s RECEIVED_ID_pscc for the Received tab. Knowing that you can call clearSelection method on your instance of plugin by adding an Execute Javascript Code Dynamic Action with a following line:

$('#RECEIVED_ID_pscc').smartCheckboxColumn('clearSelection');
Of course changing the selector accordingly to your report and column id. That should make the plugin to clear selected rows and the page item (or) collection that is used for storing values. 

Alternative: 
In general, when the page is loaded plugin reads the selected records from an item or collection and visually applies it to the state of the report rows. It has no ways of modifying item’s or collection’s values apart from the moment when you select / unselect the report rows or use the clearSelection method. This means that clearing selected rows can be also done by manually clearing the item or/and collection. If after a page refresh item/collection is empty then no rows are selected. But it often may happen that some other page elements are modifying the page item on a page load, so your trials to reset the report were unsuccessful. 
Make sure that:
If you’re using the item 
- it has no default value or source that would cause to be not null on a page load
- there’s no before-rendering process that would change item’s value
- there’s no DA triggered on page load that would modify item’s value
- item’s value is not set during redirection to a page with your report from somewhere else
- when the item was populated during redirection, the url contains the values. If you refresh the page in your browser, the values from url will be applied again even if you cleared the item before refreshing

If you’re using the collection
- there’s no before-rendering process that would change item’s value

If you’re using both collection and an item - collection values are always superior to the item. Meaning that if you manually change state of collection then after page refresh plugin will select the rows that are stored in a collection and item’s value will be adjusted. If you manually change the item, but leave the collection untouched then nothing will change after a reload, because the collection hasn’t changed.
